### ISSUE TITLE
Add support for Blueprints API

### ISSUE THREAD

**Issue by kraftner** [jdevalk/playground-embedder#1]
To be able to use this shortcode to spin up playground instances that get pre-populated with content, e.g. for use inside WP documentation the [Blueprints API](https://wordpress.github.io/wordpress-playground/docs/blueprints-api/index), specifically the [steps](https://wordpress.github.io/wordpress-playground/docs/blueprints-api/steps) would be very usefull.

I think for this shortcode the easiest way to implement it would be easing the [URL fragment approach](https://wordpress.github.io/wordpress-playground/docs/blueprints-api/using-blueprints#url-fragment):

https://playground.wordpress.net/#{%22steps%22:[{%22step%22:%22login%22},{%22step%22:%22runPHP%22,%22code%22:%22%3C?php\ninclude%20'wordpress/wp-load.php';\nwp_insert_post(array(\n'post_title'%20=%3E%20'Hello%20Playground%20Embedder',\n'post_status'%20=%3E%20'publish',\n'post_author'%20=%3E%201\n));\n%22}],%20%22landingPage%22:%20%22/wp-admin/post.php?post=4&action=edit%22}
This could either be done by putting the Blueprint JSON into a shortcode attribute or alternatively put the shortcode into the shortcode as shortcode content.

In any case the Blueprints should probably be validated/sanitized.

**Comment by jdevalk** [comment]
I actually think we should use the [JavaScript API](https://wordpress.github.io/wordpress-playground/docs/blueprints-api/using-blueprints#javascript-api) and then make the shortcode work like this:

```
[wp_playground]
{
    "landingPage": "/wp-admin/",
    "preferredVersions": {
        "php": "8.0",
        "wp": "latest"
    },
    "steps": [
        {
            "step": "login",
            "username": "admin",
            "password": "password"
        }
    ]
}
[/wp_playground]
```

Otherwise we'll run into loads of other issues with URLs being too long etc. Question is; can we use the play button thing in this API already?

**Comment by jdevalk** [comment]
Hey @kraftner, I've done a first stab at the blueprint support [here](https://github.com/jdevalk/playground-embedder/pull/3), but I get the following error using the JavaScript API:

```
Uncaught (in promise) Error: Service workers are not supported in this browser.
```

And honestly I'm stumped now :-) What am I missing?

**Comment by jdevalk** [comment]
Current output is:

```html
<iframe id="wp-3766" style="width: 800px; height: 600px"></iframe>
<script type="module">
    import { startPlaygroundWeb } from 'https://unpkg.com/@wp-playground/client/index.js';
    const client = await startPlaygroundWeb({
        iframe: document.getElementById("wp-3766"),
        remoteUrl: "https://playground.wordpress.net/remote.html?start_button=1",
        blueprint: {
    "landingPage": "\/wp-admin\/",
    "preferredVersions": {
        "php": "8.0",
        "wp": "latest"
    },
    "steps": [
        {
            "step": "login",
            "username": "admin",
            "password": "password"
        }
    ]
},
    } );
</script>
```

**Comment by kraftner** [comment]
> Hey @kraftner, I've done a first stab at the blueprint support [here](https://github.com/jdevalk/playground-embedder/pull/3), but I get the following error using the JavaScript API:
> 
> ```
> Uncaught (in promise) Error: Service workers are not supported in this browser.
> ```
> 
> And honestly I'm stumped now :-) What am I missing?

My first guess into the blue would be that you are developing locally and [Service Workers only run in a secure context](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#setting_up_to_play_with_service_workers) but this is really just a guess since this has bitten me before.

I'll have a closer look but will probably only find time in a couple of day since I need to work through the WCEU induced backlog first. :smile:

**Comment by jdevalk** [comment]
You're 100% right, it actually works already :)
